// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class PlayGameTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "lib/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void playGame() {
    driver.get("file:///Volumes/MacDisk/RSP/flexentai/RSP%20PWA%20flashcards/public/index.html");
    driver.manage().window().setSize(new Dimension(1411, 800));
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    WebElement ele=driver.findElement(By.xpath("/html/body/div[2]/button/div"));
    ele.click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    WebElement front=driver.findElement(By.cssSelector(".cont:nth-child(1) .box__face--front"));
    assertTrue(front.getText().equals("Zelenina"));
    front.click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    WebElement back=driver.findElement(By.xpath("/html/body/div[2]/div[1]/div/div[1]"));
    assertTrue(back.isDisplayed());
  }
}
